### ISSUE TITLE
ALT + F3  dmenu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#29]
check keybinding 
coincides with xfce4 keybinding to get xfce-appfinder
check on vanilla system

**Comment by Dobbie03** [comment]
We need to remove those XFCE keyboard shortcuts.  Question is, how?

**Comment by erikdubois** [comment]
let us check this on the next release

**Comment by erikdubois** [comment]
is solved now since xfce4-settings is not installed anymore

**Comment by erikdubois** [comment]
has been decided to change into xfce4-appfinder since sometimes xfce overwrites this key because of dependencies
forgotten in version 4.0
change done
