### ISSUE TITLE
Extra keybinding - tiling 

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#45]
Rajat suggested two keybindings I am using already for W-Left and W-Right.
I have a different one for W-Up and Down.
`    <keybind key="W-Up">
      <action name="MaximizeFull"/>
    </keybind>
    <keybind key="W-Down">
      <action name="UnmaximizeFull"/>
      <action name="MoveResizeTo">
        <width>80%</width>
        <height>80%</height>
      </action>
      <action name="MoveToCenter"/>
    </keybind>`

https://pastebin.com/hwzGHRGY

**Comment by erikdubois** [comment]
It is a task we should do as well... go over all the keybindings and get the best out there.

**Comment by osgyan** [comment]
I agree

**Comment by toola69** [comment]
I agree as well. We need to make them consitant @erikdubois

**Comment by Dobbie03** [comment]
Agree.  Let's make this one happen.

**Comment by erikdubois** [comment]
closing - new isssue for this
