### ISSUE TITLE
xfce4-appearance out of menu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#46]
it has been opted to NOT install it hence no menu

**Comment by Dobbie03** [comment]
XFCE4 appearance is in the menu, well should have been unless someone has removed it?
We need this installed to change GTK themes.

**Comment by erikdubois** [comment]
i thought so too... 
let us see if me run into trouble if we do not install it
it happened because of ALT+F2 and ALT+F3 
these shortctus are changed when you install xfce4-settings -> xfce4-appearance
it is back on the installation list this xfce4-settings...
it might be as well on the application list again
ok putting it back in...
