### ISSUE TITLE
Menu adapation for dmenu and arandr

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#47]
Can I let dmenu and arandr come up one level?
No need to have a submenu any more?
![dmenu](https://cloud.githubusercontent.com/assets/10594806/24617238/ab82e138-1893-11e7-86a8-24ed9e3d8f19.jpg)

**Comment by Dobbie03** [comment]
Yes go for it Erik.

**Comment by erikdubois** [comment]
done
