### ISSUE TITLE
add preferred applications to the menu list.

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#48]
exo-preferred-applications sets your terminal, filemanager etc.

**Comment by Dobbie03** [comment]
Yes, maybe this could go under settings.

**Comment by erikdubois** [comment]
do you mean the menu preferences ?

**Comment by Dobbie03** [comment]
Sorry yes the Preferences Menu

**Comment by erikdubois** [comment]
how about just above power managerment

**Comment by Dobbie03** [comment]
That's a thumbs up from me.

**Comment by erikdubois** [comment]
done
