### ISSUE TITLE
Finetuning of menu.xml - coming to terms what goes in, what goes to personal section

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#53]
to @ARCHLabs/core-members 
i have made a structure in BOTH menu.xml and rc.xml.
The idea is to actually use the menu of archlabs... so we come across mistakes ourselves.

We have now our menu (which looks great) - let us streamline this further.
e.g. I do not like the part of the screenshots
e.g. in multimedia do we need these categories - i do not think so
e.g. some of these menu's are chaotic make them alphabetic 

Then at the bottom-end after exit we can add our personal menu's... this will make it easy to reintegrate the new archlabs menu with our personal one later on in the next releases 

![2017-04-07--1491548932_3840x1080_scrot](https://cloud.githubusercontent.com/assets/10594806/24789141/d9291662-1b71-11e7-8019-c8f28e171d7f.png)

Every menu item should be clicked and checked to make the next edition full-proof.

**Comment by toola69** [comment]
@erikdubois for sure

**Comment by Dobbie03** [comment]
The menu structure follows the BL structure.  If there are applications we are adding specific to AL that BL don't use, I think we need to make a AL specific menu entry.

**Comment by erikdubois** [comment]
i think we can close this one
we follow the bl structure
