### ISSUE TITLE
Finetuning of rc.xml - coming to terms what goes in, what goes to personal section

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#54]
to @ARCHLabs/core-members
I have made a structure in BOTH menu.xml and rc.xml.
The idea is to get the best keybindings out there for archlabs
This was the most difficult task if you can believe it. 
**Pure chaos.** Meld tried to do its best... 
Do not shoot me if I deleted or changed stuff. 
Be patient with it and learn the new keyboard shortcuts like I have learned your new keyboard shortcuts.
Let us compare our personal rc.xml files and use this file as a template.
It has been structured via categories (sound,...) or via keyboard shorcut affinity like starting with ctrl+alt+

If you see mistakes, please correct them. 
If you can add new shortcuts, please add them. 
If you want to delete icons, DO NOT DELETE THEM. Put them for now at the bottom of the keyboard shortcut list just before < / keyboard >
![keyboard](https://cloud.githubusercontent.com/assets/10594806/24789385/113df8be-1b73-11e7-8484-3b28d49da1de.png)

Use ./git-vx.sh to push it back online for others to use it.

We may/will need to reopen issues what to install out of the box and what not. Since some of the keyboard shortcuts are pointing to software that is not yet installed like variety, meld, virtualbox, spotify.
These will be typically shortcuts that will move to the bottom of the rc.xml. They will be included in the personal section at our local machines and will be left out in the official distro release. I hope I am making sense to you all.

**Comment by Dobbie03** [comment]
Good work Erik, might be an idea to include this with the new testing release so we can all try them out.

**Comment by erikdubois** [comment]
no input closing for now
