### ISSUE TITLE
Menu's running with sudo take a long time

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#56]
filemanager as root
texteditor as root
loginsettings...

we need to figure this out
is maybe related to the fact that pamac-updater is NOT asking a root password...?

**Comment by erikdubois** [comment]
@toola69 reported that it works fine on his machine?
others?

**Comment by Dobbie03** [comment]
Once I had a reboot this issue disappeared.

**Comment by Dobbie03** [comment]
Confirming this issue has reappeared.  At this point I can get anything to open with sudo.

**Comment by erikdubois** [comment]
i do think it is gone after a reboot

**Comment by Dobbie03** [comment]
Hmmm, three reboots later and now Thunar and Geany are opening immediately with sudo.

**Comment by erikdubois** [comment]
i think we can close this one now.

**Comment by erikdubois** [comment]
consensus with @Dobbie03 to close
