### ISSUE TITLE
lightdmgreeter finetuning - menu preferences

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#57]
points to arc-dark-grey that is not installed now
let us make a nice archlab lightdmgreeter

**Comment by Dobbie03** [comment]
We can use the new Bunsen-Dark-He for the LightDM greeter theme.

**Comment by erikdubois** [comment]
take picture and lets vote on it

**Comment by erikdubois** [comment]
done
