### ISSUE TITLE
message from virtualbox

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#59]
on an ssd we get a message coming from 
/etc/xdg/autostart/vboxclient.desktop
we need the cleanup.sh to work + we need a switch between virtualbox and ssd

**Comment by erikdubois** [comment]
@ajjames31 can you shed a light how to proceed here ?

**Comment by Dobbie03** [comment]
Has this been added to the cleanup script?

**Comment by erikdubois** [comment]
no
we need to find a way to know when to run the script and when not to

**Comment by Dobbie03** [comment]
A welcome script similar to the BL one is looking more and more like something we are going to have to get sorted.

**Comment by erikdubois** [comment]
consensus with @Dobbie03 to close
on short term we will use scripts to assists users to delete virtualbox software
