### ISSUE TITLE
obmenu-generated menu added

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#62]
i have added a menu-obmenu-generator.xml to the folder.
First install the application
`sudo pacman -S obmenu-generator `
Then rename the menu.xml to menu-default.xml for example.
Rename menu-obmenu-generator.xml to menu.xml. 
Do not reload yet.
First copy/paste over the rest of the files from [this github](https://github.com/ARCHLabs/Archlabs-Other-Config-Files/tree/master/config/obmenu-generator).

Copy/paste the two files from obmenu-generator folder in your ~/.config/obmenu-generator folder

Only then restart openbox

I have kept the same structure as the default menu.

**Comment by Dobbie03** [comment]
As long as obmenu-generator doesn't override the default menu order then I am all for inclusion.

**Comment by erikdubois** [comment]
It does not override the default menu. It is another file next to the menu.xml.  @toola69  is thinking about a script to switch from default to generated menu and back... that is for me an enhancement and further down the road

**Comment by erikdubois** [comment]
on google hangout decided it works for all
