### ISSUE TITLE
ctrl+alt+backspace

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#63]
now it restarts the openbox
maybe it is better to start openbox reconfigure
no problem with conky blur
and 
works when you change a keyboard shortcut and a menu change
confirm this please

**Comment by erikdubois** [comment]
what should I do here? @Dobbie03

**Comment by Dobbie03** [comment]
Leave it in but make the command "openbox --reconfigure"

**Comment by erikdubois** [comment]
that would be my suggestion as well
in release 3.6.6
