### ISSUE TITLE
Desktop Names - obconf/rc.xml

### ISSUE THREAD

**Issue by yodayogi** [ARCHLabs/Archlabs-Openbox-Configs#69]
If the number of desktops is reduced using obconf (GUI Config Tool) to say 2 or 1, the desktop names list still shows 4 desktops.  The expected behavior is the desktop names list should reduce to either 2 or 1.
![image](https://user-images.githubusercontent.com/28506119/27031496-2044b178-4f8e-11e7-8ab8-a09fd4bebc16.png)

Also, if the number of desktops is increased to say 5 or 6, then the values for additional desktops is displayed as Unnamed Desktop.  This breaks the consistency in the naming of desktops.
![image](https://user-images.githubusercontent.com/28506119/27031531-4a7a9174-4f8e-11e7-9360-c51894ff4fa4.png)

Looks like the desktop names are hard coded in the rc.xml file which could be causing the issue.  Recommend that we let openbox handle the desktop naming as per its defaults to maintain consistency.

**Comment by erikdubois** [comment]
we will look into it?
I wonder if this  occur also in Manjaro/Antergos
then is is more an openbox issue...
Investigation required

**Comment by Dobbie03** [comment]
This possibly could be a hold over from +1.

**Comment by erikdubois** [comment]
![2017-06-19--1497883531_1600x900_scrot](https://user-images.githubusercontent.com/10594806/27290971-1ac7b05c-550f-11e7-8473-39406e9e10ca.png)

as long as the result is ok then I have no problem with it
next time i install manjaro or antergos i will check if they have the same issue
closing for now
