### ISSUE TITLE
obmenu-generated menu as standard

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#72]
How about having the obmenu generated menu as standard. Piping menu without icons.
It will give a better view of all installed software for starters of ArchLabs.
From tutorials online I deduct that many issues/frustrations can be avoided IF they would have know other ways (menu's) to get to the applications.

**Comment by darknetmatrix** [comment]
That would not be a bad decision imo

**Comment by Dobbie03** [comment]
I'd like to see a non obmenu generated menu vs. a obmenu generated menu before giving my two cents on this.

**Comment by erikdubois** [comment]
let us keep the standard menu
many things have been added so users will there way
![2017-06-16](https://user-images.githubusercontent.com/10594806/27278060-93ef0f86-54e0-11e7-9c4d-a7305a11f3b7.gif)
