### ISSUE TITLE
Move conky chooser pipemenu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Openbox-Configs#80]
can we move the conky chooser higher up the menu
takes a long time to navigate to something you often use
input : sudo reboot

**Comment by natemaia** [comment]
I am ok with It could be pushed up into the preferences menu.
One problem I see us having is the menu in openbox is supposed to be light and not feel encumbersome
and the user is meant to be using a launcher and not have every possible application lumped into the menu
If we push too many things higher in the menu it becomes rather large

**Comment by Dobbie03** [comment]
Not really an issue.  Closing.
