### ISSUE TITLE
Super +X multiple hit issue

### ISSUE THREAD

**Issue by vinodsr** [ARCHLabs/Archlabs-Openbox-Configs#83]
Try hitting the `Super + X` combination , the exit menu will appear. Try hitting the same key combination. You can see as many exit menu coming in and you need to press `esc` many times to go back to desktop.

**Comment by erikdubois** [comment]
You are quite right. I have never pressed it twice before i all these months.
We will look into it.

**Comment by erikdubois** [comment]
Plan B

#!/bin/bash

START='oblogout'
STOP="pkill oblogout"

if pgrep -x oblogout > /dev/null
then
$STOP
else
$START
fi

exit 0
