### ISSUE TITLE
Change Alt-Tab behaviour

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Openbox-Configs#84]
Best way to explain is for you to change your alt-tab in rc.xml to:

  <keybind key="A-Tab">
     <action name="NextWindow">
         <raise>yes</raise>
       <finalactions>
         <action name="Focus"/>
         <action name="Raise"/>
         <action name="Unshade"/>
       </finalactions>
     </action>
   </keybind>

Credit to Snow/Smoke King

**Comment by natemaia** [comment]
You can try out this, I just found out there is one action to both raise and unshade :)
```
    <keybind key="A-Tab">
      <action name="NextWindow">
        <raise>yes</raise>
        <finalactions>
          <action name="Focus"/>
          <action name="UnshadeRaise"/>
        </finalactions>
      </action>
    </keybind>
```

**Comment by erikdubois** [comment]
Keymenu no problems?
