### ISSUE TITLE
Screenshot error with non english Locales

### ISSUE THREAD

**Issue by nori971** [ARCHLabs/Archlabs-Openbox-Configs#86]
When taking a screenshot the file is moved from current to the picture folder which path has been hardcoded to it's english name, this is showing an error for archlabs installations with language other than english.

**Comment by addy-dclxvi** [comment]
Yup, It should be changed to ~/Pictures.
For temporary solution, edit your rc.xml. Or if you are taking screenshot from Openbox right click main menu, please edit your menu.xml

**Comment by addy-dclxvi** [comment]
Upps, I mean It should be changed to home, not ~/Pictures

**Comment by natemaia** [comment]
Thank you for the contribution, a much cleaner solution.
